#!/usr/bin/env node

function parse(dirty){
  const createDOMPurify = require('dompurify');
  const { Readability } = require('@mozilla/readability');
  const { JSDOM } = require('jsdom');
  
  const window = new JSDOM("").window;
  const DOMPurify = createDOMPurify(window);
  
  const clean = DOMPurify.sanitize(dirty);
  
  const doc = new JSDOM(clean, {
    url: "https://www.example.com/the-page-i-got-the-source-from"
  });
  
  const reader = new Readability(doc.window.document);
  const article = reader.parse();
  return article;
}

const source_path = process.argv[2];
if(source_path == "--version"){
  console.log("0.1.0")
}

process.stdin.setEncoding('utf8');
var chunk, chunks, content;
chunks = [];
process.stdin.on('end', () => {
	content = chunks.join('');
  process.stdout.write(JSON.stringify(parse(content)));
});
process.stdin.on('readable', () => {
  let chunk;
  // Use a loop to make sure we read all available data.
  while ((chunk = process.stdin.read()) !== null) {
	  chunks.push(chunk);
  }
});

